services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - test_net
    volumes:
      - test_vol:/data
    restart: unless-stopped

networks:
  test_net:
    external: true

volumes:
  test_vol:
    external: true
